name: Publish

on:
  # When Release Pull Request is merged
  pull_request:
    branches:
      - master
    types: [closed]

env:
  DOCKER_BASE_NAME: ghcr.io/${{ github.repository }}
  DOCKER_HUB_BASE_NAME: secretlint/secretlint

jobs:
  publish:
    if: |
      github.event.pull_request.merged == true &&
      contains(github.event.pull_request.labels.*.name, 'Type: Release')
    runs-on: ubuntu-latest
    environment: npm
    permissions:
      contents: write
      id-token: write  # Required for OIDC
    outputs:
      exists_tag: ${{ steps.tag_check.outputs.exists_tag }}
      version: ${{ env.CURRENT_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      - name: Git Identity
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        run: pnpm install
      # Define ${CURRENT_VERSION}
      - name: Set Current Version
        run: |
          CURRENT_VERSION=$(node -p 'require("./package.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Tag Check
        id: tag_check
        run: |
          GET_API_URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/v${CURRENT_VERSION}"
          http_status_code=$(curl -LI $GET_API_URL -o /dev/null -w '%{http_code}\n' -s \
            -H "Authorization: token ${GITHUB_TOKEN}")
          if [ "$http_status_code" -ne "404" ] ; then
            echo "exists_tag=true" >> $GITHUB_OUTPUT
          else
            echo "exists_tag=false" >> $GITHUB_OUTPUT
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish with OIDC
        if: steps.tag_check.outputs.exists_tag == 'false'
        run: |
          pnpm -r publish --no-git-checks
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
      - name: Create Git Tag
        if: steps.tag_check.outputs.exists_tag == 'false'
        uses: pkgdeps/git-tag-action@a5a161774bace8b4e1969dd850c67a7421f1b710 # v3.0.1
        with:
          version: ${{ env.CURRENT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

  publish-binary:
    needs: [publish]
    if: needs.publish.outputs.exists_tag == 'false'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
      - name: Install
        run: pnpm install
      - name: Build Source Code
        run: pnpm run build
      # build the binary
      - name: Setup Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2.2.0 # zizmor: ignore[cache-poisoning]
        with:
          bun-version-file: "./publish/binary-compiler/.bun-version"
      - name: Build binary
        run: bun run build-binary
        working-directory: ./publish/binary-compiler
      - name: Upload binary artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: binary-dist
          path: ./publish/binary-compiler/dist/**

  publish-docker:
    needs: [publish]
    if: needs.publish.outputs.exists_tag == 'false'
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Set TAG_NAME
        run: |
          echo "TAG_NAME=v${{ needs.publish.outputs.version }}" >> $GITHUB_ENV
          echo "SECRETLINT_VERSION=${{ needs.publish.outputs.version }}" >> $GITHUB_ENV
      - name: Set HUB_TAG
        run: |
          echo "PKG_TAG=${DOCKER_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
          echo "PKG_LATEST_TAG=${DOCKER_BASE_NAME}:latest" >> $GITHUB_ENV
          echo "HUB_TAG=${DOCKER_HUB_BASE_NAME}:${TAG_NAME}" >> $GITHUB_ENV
          echo "HUB_LATEST_TAG=${DOCKER_HUB_BASE_NAME}:latest" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0
        with:
          image: tonistiigi/binfmt:qemu-v9.2.2@sha256:1b804311fe87047a4c96d38b4b3ef6f62fca8cd125265917a9e3dc3c996c39e6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4.0.0
      - name: Login to Registries
        run: |
          echo "${GITHUB_TOKEN}" | docker login ghcr.io -u azu --password-stdin
          echo "${DOCKER_HUB_TOKEN}" | docker login -u efcl --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build image
        run: |
          docker buildx build . \
            --build-arg SECRETLINT_VERSION=${SECRETLINT_VERSION} \
            --load \
            -t "${PKG_TAG}"
        working-directory: ./publish/docker
      - name: Print version
        run: |
          docker run --rm ${PKG_TAG} --version
        working-directory: ./publish/docker
      - name: Build and push images
        run: |
          docker buildx build . \
            --build-arg SECRETLINT_VERSION=${SECRETLINT_VERSION} \
            --platform linux/amd64,linux/arm64 \
            --push \
            -t "${PKG_TAG}" \
            -t "${PKG_LATEST_TAG}" \
            -t "${HUB_TAG}" \
            -t "${HUB_LATEST_TAG}"
        working-directory: ./publish/docker

  create-release:
    needs: [publish, publish-binary]
    if: needs.publish.outputs.exists_tag == 'false'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Download binary artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: binary-dist
          path: ./binary-dist
      - name: Create Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.publish.outputs.version }}
          name: ${{ github.event.pull_request.title }}
          body: |
            ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
          files: ./binary-dist/**
      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version = '${{ needs.publish.outputs.version }}';
            const repository = process.env.GITHUB_REPOSITORY;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🎉 Release https://github.com/${repository}/releases/tag/v${version}`
            })
